/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AuthoritiesRouteImport } from './routes/authorities'
import { Route as AuthorityRouteImport } from './routes/authority'
import { Route as BillboardRouteImport } from './routes/billboard'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DetectionRouteImport } from './routes/detection'
import { Route as EscalationRouteImport } from './routes/escalation'
import { Route as GroupingRouteImport } from './routes/grouping'
import { Route as IotRouteImport } from './routes/iot'
import { Route as MapRouteImport } from './routes/map'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as PotholeIdRouteImport } from './routes/pothole.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthoritiesRoute = AuthoritiesRouteImport.update({
  id: '/authorities',
  path: '/authorities',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorityRoute = AuthorityRouteImport.update({
  id: '/authority',
  path: '/authority',
  getParentRoute: () => rootRouteImport,
} as any)
const BillboardRoute = BillboardRouteImport.update({
  id: '/billboard',
  path: '/billboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DetectionRoute = DetectionRouteImport.update({
  id: '/detection',
  path: '/detection',
  getParentRoute: () => rootRouteImport,
} as any)
const EscalationRoute = EscalationRouteImport.update({
  id: '/escalation',
  path: '/escalation',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupingRoute = GroupingRouteImport.update({
  id: '/grouping',
  path: '/grouping',
  getParentRoute: () => rootRouteImport,
} as any)
const IotRoute = IotRouteImport.update({
  id: '/iot',
  path: '/iot',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const PotholeIdRoute = PotholeIdRouteImport.update({
  id: '/pothole/$id',
  path: '/pothole/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/architecture': typeof ArchitectureRoute
  '/assistant': typeof AssistantRoute
  '/authorities': typeof AuthoritiesRoute
  '/authority': typeof AuthorityRoute
  '/billboard': typeof BillboardRoute
  '/dashboard': typeof DashboardRoute
  '/detection': typeof DetectionRoute
  '/escalation': typeof EscalationRoute
  '/grouping': typeof GroupingRoute
  '/iot': typeof IotRoute
  '/map': typeof MapRoute
  '/reports': typeof ReportsRoute
  '/verification': typeof VerificationRoute
  '/pothole/$id': typeof PotholeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/architecture': typeof ArchitectureRoute
  '/assistant': typeof AssistantRoute
  '/authorities': typeof AuthoritiesRoute
  '/authority': typeof AuthorityRoute
  '/billboard': typeof BillboardRoute
  '/dashboard': typeof DashboardRoute
  '/detection': typeof DetectionRoute
  '/escalation': typeof EscalationRoute
  '/grouping': typeof GroupingRoute
  '/iot': typeof IotRoute
  '/map': typeof MapRoute
  '/reports': typeof ReportsRoute
  '/verification': typeof VerificationRoute
  '/pothole/$id': typeof PotholeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/architecture': typeof ArchitectureRoute
  '/assistant': typeof AssistantRoute
  '/authorities': typeof AuthoritiesRoute
  '/authority': typeof AuthorityRoute
  '/billboard': typeof BillboardRoute
  '/dashboard': typeof DashboardRoute
  '/detection': typeof DetectionRoute
  '/escalation': typeof EscalationRoute
  '/grouping': typeof GroupingRoute
  '/iot': typeof IotRoute
  '/map': typeof MapRoute
  '/reports': typeof ReportsRoute
  '/verification': typeof VerificationRoute
  '/pothole/$id': typeof PotholeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/architecture'
    | '/assistant'
    | '/authorities'
    | '/authority'
    | '/billboard'
    | '/dashboard'
    | '/detection'
    | '/escalation'
    | '/grouping'
    | '/iot'
    | '/map'
    | '/reports'
    | '/verification'
    | '/pothole/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/architecture'
    | '/assistant'
    | '/authorities'
    | '/authority'
    | '/billboard'
    | '/dashboard'
    | '/detection'
    | '/escalation'
    | '/grouping'
    | '/iot'
    | '/map'
    | '/reports'
    | '/verification'
    | '/pothole/$id'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/architecture'
    | '/assistant'
    | '/authorities'
    | '/authority'
    | '/billboard'
    | '/dashboard'
    | '/detection'
    | '/escalation'
    | '/grouping'
    | '/iot'
    | '/map'
    | '/reports'
    | '/verification'
    | '/pothole/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ArchitectureRoute: typeof ArchitectureRoute
  AssistantRoute: typeof AssistantRoute
  AuthoritiesRoute: typeof AuthoritiesRoute
  AuthorityRoute: typeof AuthorityRoute
  BillboardRoute: typeof BillboardRoute
  DashboardRoute: typeof DashboardRoute
  DetectionRoute: typeof DetectionRoute
  EscalationRoute: typeof EscalationRoute
  GroupingRoute: typeof GroupingRoute
  IotRoute: typeof IotRoute
  MapRoute: typeof MapRoute
  ReportsRoute: typeof ReportsRoute
  VerificationRoute: typeof VerificationRoute
  PotholeIdRoute: typeof PotholeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authorities': {
      id: '/authorities'
      path: '/authorities'
      fullPath: '/authorities'
      preLoaderRoute: typeof AuthoritiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authority': {
      id: '/authority'
      path: '/authority'
      fullPath: '/authority'
      preLoaderRoute: typeof AuthorityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billboard': {
      id: '/billboard'
      path: '/billboard'
      fullPath: '/billboard'
      preLoaderRoute: typeof BillboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detection': {
      id: '/detection'
      path: '/detection'
      fullPath: '/detection'
      preLoaderRoute: typeof DetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escalation': {
      id: '/escalation'
      path: '/escalation'
      fullPath: '/escalation'
      preLoaderRoute: typeof EscalationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grouping': {
      id: '/grouping'
      path: '/grouping'
      fullPath: '/grouping'
      preLoaderRoute: typeof GroupingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iot': {
      id: '/iot'
      path: '/iot'
      fullPath: '/iot'
      preLoaderRoute: typeof IotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pothole/$id': {
      id: '/pothole/$id'
      path: '/pothole/$id'
      fullPath: '/pothole/$id'
      preLoaderRoute: typeof PotholeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  ArchitectureRoute: ArchitectureRoute,
  AssistantRoute: AssistantRoute,
  AuthoritiesRoute: AuthoritiesRoute,
  AuthorityRoute: AuthorityRoute,
  BillboardRoute: BillboardRoute,
  DashboardRoute: DashboardRoute,
  DetectionRoute: DetectionRoute,
  EscalationRoute: EscalationRoute,
  GroupingRoute: GroupingRoute,
  IotRoute: IotRoute,
  MapRoute: MapRoute,
  ReportsRoute: ReportsRoute,
  VerificationRoute: VerificationRoute,
  PotholeIdRoute: PotholeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
